### ISSUE TITLE
Move to new philosophy of package

### ISSUE THREAD

**Issue by m-thalmann** [m-thalmann/laravel-token-auth#7]
Currently this package allows to generate Refresh Tokens and Access Tokens, both of which are stored to the database. Since (most of the time) they are generated in pairs and one can't exist without the other, it would be better to just store the Refresh Tokens, whereas the Access Tokens have encoded the group-id and a signature for it (somewhat like JWT). There should also be possibilities to create "standalone" Access Tokens with special permissions and a more easy way to create new tokens / pairs.

### ToDo

- [x] Distinguish between Token-Pair-Access-Tokens and "standalone" Access Tokens
- [x] Better / easier way to create new Tokens (-Pairs)
- [x] (Don't use static Methods, use a Facade instead)
- [x] More customization options for:
   - Retrieving of token from request
   - Setting/Retrieving user
   - Authenticating a request (even when no token is present)
   - ...
...
